api/urls.py
from django.urls import path, re_path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from api.views import (
    ChangeRequestAPIView,
    CompanyUpdatesAPIView,
    DNBCompanyHierarchySearchAPIView,
    DNBCompanyHierarchySearchCountAPIView,
    DNBCompanySearchAPIView,
    DNBCompanySearchV2APIView,
    InvestigationAPIView,
)

app_name = "api"

urlpatterns = [
    path("companies/search/", DNBCompanySearchAPIView.as_view(), name="company-search"),
    path(
        "v2/companies/search/",
        DNBCompanySearchV2APIView.as_view(),
        name="company-search-v2",
    ),
    path(
        "companies/hierarchy/search/",
        DNBCompanyHierarchySearchAPIView.as_view(),
        name="company-hierarchy-search",
    ),
    path(
        "companies/hierarchy/search/count",
        DNBCompanyHierarchySearchCountAPIView.as_view(),
        name="company-hierarchy-search-count",
    ),
    path("companies/", CompanyUpdatesAPIView.as_view(), name="company-updates"),
    path("change-request/", ChangeRequestAPIView.as_view(), name="change-request"),
    path("investigation/", InvestigationAPIView.as_view(), name="investigation"),
    re_path(r"^swagger\.(?P<format>json|yaml)$", SpectacularAPIView.as_view(), name="schema-json"),
    re_path(r"^swagger/$", SpectacularSwaggerView.as_view(url_name='api:schema-json'), name="schema-swagger-ui"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from core.admin_views import admin_login_view
from health_check.views import HealthCheckP1View

auth_urls = []

if settings.ENABLE_STAFF_SSO:
    auth_urls = [
        path('auth/', include('authbroker_client.urls', namespace='authbroker')),
        path('admin/login/', admin_login_view),
    ]

urlpatterns = [
    *auth_urls,
    path('admin/', admin.site.urls),
    path('api/workspace/', include('workspace.urls', namespace='workspace')),
    path('api/', include('api.urls', namespace='api')),
    path('healthcheck/', include('health_check.urls', namespace='healthcheck')),
    path('pingdom/ping.xml', HealthCheckP1View.as_view(), name='pingdom'),
    path('', include('django_prometheus.urls')),
]

console/urls.py
from django.urls import path

from .views import SearchView, DetailView

app_name = 'console'

urlpatterns = [
    path('', SearchView.as_view(), name='search'),
    path('detail/<int:duns>/', DetailView.as_view(), name='detail'),
]

console/forms.py
from django import forms

from govuk_forms.forms import GOVUKForm
from govuk_forms import widgets

from dnb_worldbase.constants import DNB_COUNTRY_CODE_MAPPING

from .constants import ISO_COUNTRY_CHOICES

COUNTRIES = set(DNB_COUNTRY_CODE_MAPPING.values())

DEFAULT_PAGE_SIZE = 10

PAGE_SIZE_CHOICES = (
    (10, '10'),
    (20, '20'),
    (30, '30'),
    (40, '40'),
    (50, '50'),
)


class SearchForm(GOVUKForm):
    searchTerm = forms.CharField(
        label='Company name',
        help_text='Search companies primary or trading names',
        required=True,
        widget=widgets.TextInput(),
    )
    countryISOAlpha2Code = forms.ChoiceField(
        label='Country',
        required=False,
        widget=widgets.Select(),
        choices=ISO_COUNTRY_CHOICES,
        initial='GB',
    )
    isOutOfBusiness = forms.BooleanField(
        label='Is out of business?',
        help_text='Return companies that are out of business',
        initial=False,
        required=False,
        widget=widgets.CheckboxInput(),
    )
    pageSize = forms.TypedChoiceField(
        label='Number of results',
        initial=10,
        widget=widgets.Select(),
        choices=PAGE_SIZE_CHOICES,
        coerce=int,
    )

console/views.py
import requests
from json2html import json2html

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import FormView
from django.views.generic.base import TemplateView

from dnb_api.client import api_request, DNB_COMPANY_SEARCH_ENDPOINT
from .forms import SearchForm


@method_decorator(login_required, name='dispatch')
class SearchView(FormView):
    form_class = SearchForm
    template_name = 'search.html'

    def form_valid(self, form):

        try:
            response = api_request('POST', DNB_COMPANY_SEARCH_ENDPOINT, json=form.cleaned_data)

        except requests.exceptions.HTTPError as err:
            if err.response.status_code == 404:
                results = 'No matching results. Try again.'
            else:
                raise
        else:
            results = [{'raw': result['organization'], 'html': json2html.convert(result['organization'])}
                       for result in response.json()['searchCandidates']]

        context = self.get_context_data()
        context['results'] = results

        return self.render_to_response(context)


@method_decorator(login_required, name='dispatch')
class DetailView(TemplateView):
    template_name = 'detail.html'

    def get(self, request, duns, *args, **kwargs):
        #api_endpoint = f'https://plus.dnb.com/v1/data/duns/{duns}?productId=cmptcs&versionId=v1'
        api_endpoint = f'https://plus.dnb.com/v1/data/duns/{duns}?productId=cmpelk&versionId=v2'

        try:
            response = api_request('GET', api_endpoint)

        except requests.exceptions.HTTPError as err:
            import pdb; pdb.set_trace()
            if err.response.status_code == 404:
                results = 'No matching results.'
            else:
                raise
        except Exception as ex:
            import pdb; pdb.set_trace()
        else:
            data = response.json()['organization']
            result = {
                'raw': data,
                'html': json2html.convert(data, clubbing=False)
            }

        context = self.get_context_data(**kwargs)
        context['result'] = result

        return self.render_to_response(context)

console/templates/detail.html
{% extends 'govuk_template.html' %}

{% block inner_content %}

<h1 class="heading-large">Company details</h1>

{{ result.html|safe }}

{% endblock %}

console/templates/search.html
{% extends 'govuk_template.html' %}

{% block head %}
{{ block.super }}
<script
        src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
        crossorigin="anonymous"></script>
<script type="text/javascript">
    $(document).ready(function (e) {
        $('a.expand').click(function () {

            var id = '#' + $(this).attr('rel');

            $(id).toggle();

            $("body,html").animate(
                {
                    scrollTop: $(id).offset().top
                },
                5000
            );

            return false;
        });
    });
</script>
{% endblock %}

{% block inner_content %}
<p>
<h1 class="heading-large">Company search</h1>
<form method="post" action="{{ request.post }}">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="button" value="Search"/>
</form>
</p>

{% if results %}

<p>
<h2 id="results" class="heading-large">Search results</h2>

{% for result in results %}
<h3 class="heading-medium">Name: {{ result.raw.primaryName }}</h3>
<table class="company-summary">
    <tr>
        <td>Duns</td>
        <td>{{ result.raw.duns }}</td>
        <td>Country</td>
        <td>{{ result.raw.primaryAddress.addressCountry.isoAlpha2Code }}</td>
    </tr>
    <tr>
        <td>Business entity</td>
        <td>{{ result.raw.businessEntityType.description }}</td>
        <td>Yearly revenue</td>
        <td>{{ result.raw.financials.0.yearlyRevenue.0.value }} {{ result.raw.financials.0.yearlyRevenue.0.currency }}</td>
    </tr>
    <tr>
        <td colspan="2"><a href="#" rel="data_{{ forloop.counter }}" class="expand">View raw data</a></td>
        <td colspan="2"><a href="{% url 'console:detail' duns=result.raw.duns %}">View detailed company data</a></td>
    </tr>
</table>

<div style="display: none" id="data_{{ forloop.counter }}">
    {{ result.html|safe }}
</div>
{% endfor %}
</p>
{% endif %}

{% endblock %}